### PR TITLE
Showcase Validation check

### PR DESCRIPTION
**Pull request by Usagib**

### CODE REVIEW

**Comment by Usagib** [comment]
Hello Team!
I have finished my framework project called stylo and cloned cnn.com webpage, validation and style corrections done.
Happy coding!

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi @Usagib,

### Amazing job, :raised_hands: Your page looks uniquely awesome! Just some more requirements to wrap it up:

### Box utilities

#### Margins

* [x] The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
* [x] The margins should span from `0 rem` to `1 rem`
* [x] The margins should have breakpoints (e.g. margin-sm-top-1)

#### Padding

* [x] The CSS files define separate classes for padding-top, bottom, left, right, all padding and auto
* [x] The padding should span from `0 rem` to `1 rem`
* [x] The padding should have breakpoints (example padding-lg-2)

### Positioning

#### Floats

* [x] The CSS files define separate classes for float left, right and clearing the floats

#### Positions

* [x] The CSS files define separate classes to change the position property of an element to relative, absolute or fixed

### Display

#### Display properties

The CSS files define:

* [x] A class to set the display property of an element to flex
* [x] A class to set the display property to hidden
* [x] A class to set the display property to none
* [x] The none class should have breakpoints (example display-md-none)

#### Flex properties

The CSS files define:

* [x] Classes to set vertical alignment as top, bottom or center
* [x] Classes to set horizontal alignment as left, right or center

### Colors

#### Background and text

The CSS files define:

* [x] At least ten different classes to set the background and text colors of an element

### Text

#### Utilities

The CSS files define:

* [x] Classes to horizontally align text to the left, right or center
* [x] At least five classes to set the font size of an element
* [x] Three classes to set the font-weight of an element (bold, normal, medium)

#### Border

* [x] The CSS files define separate classes for border-top, bottom, left, right, all border
* [x] The border should span from 0 to 1rem
* [x] The border should have classes for making box round
* [x] The border should have a class defined to transform a box into a circle

I know this seems like a lot, but that's why it's called a framework. Your previous code tells me this isn't a mountain that's too high to climb for you. 

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_

**Comment by Usagib** [comment]
Hi team!
Changes finished also added to the readme doc
awaiting review
happy coding!!!

**Comment by shshamim63** [comment]
### Status :tada:  Approved :tada: 
___
Hi @Usagib :wave: ,
Well done, I can see. most of the task has been covered. There is an empty media query on your style.css file. https://github.com/Usagib/stylofw/blob/c290f7a32e3d2e2581bf8cf01ce1435cceb64afc/css/style.css#L220.
Please delete it.
##### This :+1:  is from me. You can merge it. Don't forget to fill the project completion form.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawat-hossain-7750b0127/)|[Slack](Shakhawat Hossain)

**Comment by Usagib** [comment]
thank you! last adjustment made, merging pull request to master

**Pull request merged**
